export const currentUser = {
  name: "Alex Morgan",
  email: "alex.morgan@studio.co",
  initials: "AM",
};

const conversations = [
  [
    "Sophia Chen",
    "sophia@studio.co",
    "Website redesign — ready for your review",
    "Hey Alex, the latest designs are ready! I’ve incorporated the feedback from our last session.",
    "10:42 AM",
    "Projects",
    true,
    true,
    "SC",
    "violet",
    "Hey Alex,\n\nThe latest website designs are ready for your review! I’ve incorporated the feedback from our last session, especially around the navigation and the new product pages.\n\nHere’s a quick rundown of what’s new:\n• A simpler navigation with clearer paths to our products\n• Updated typography and a fresh, more consistent color palette\n• A mobile-first approach to the product detail pages\n\nI’ve attached the design brief so you have all the context. Would love to get your thoughts before we share this with the wider team on Thursday.\n\nThanks for all your input on this — it’s coming together really nicely!\n\nBest,\nSophia",
    "Website redesign brief.txt",
  ],
  [
    "James Wilson",
    "james@studio.co",
    "A quick sync before the launch?",
    "Are you free tomorrow at 11? Would love to align on the final launch checklist.",
    "10:18 AM",
    "Work",
    true,
    false,
    "JW",
    "blue",
  ],
  [
    "Notion",
    "team@email.notion.so",
    "Your weekly workspace digest",
    "A little recap of what your team has been working on this week.",
    "9:56 AM",
    "Updates",
    false,
    false,
    "N",
    "slate",
  ],
  [
    "Emma Davis",
    "emma@studio.co",
    "Brand assets are good to go",
    "Sharing the final brand assets. Thanks everyone for the thoughtful feedback!",
    "9:30 AM",
    "Projects",
    true,
    true,
    "ED",
    "pink",
  ],
  [
    "Product team",
    "product@studio.co",
    "September roadmap · a few updates",
    "Hi team, here’s where we are with our priorities for the month.",
    "9:05 AM",
    "Work",
    false,
    false,
    "PT",
    "green",
  ],
  [
    "Figma",
    "updates@figma.com",
    "A few new things to make your day",
    "New features, little improvements, and a little inspiration for your next big idea.",
    "8:42 AM",
    "Updates",
    false,
    false,
    "F",
    "orange",
  ],
  [
    "Liam Anderson",
    "liam@studio.co",
    "Coffee and a catch-up?",
    "It’s been a minute! There’s a new place near the studio I think you’d like.",
    "Yesterday",
    "Personal",
    false,
    false,
    "LA",
    "teal",
  ],
  [
    "Olivia Martinez",
    "olivia@studio.co",
    "Q3 campaign performance report",
    "The numbers are in, and there’s a lot to be excited about. Take a look!",
    "Yesterday",
    "Work",
    false,
    true,
    "OM",
    "violet",
  ],
  [
    "Dribbble",
    "hello@dribbble.com",
    "Your daily dose of design inspiration",
    "A handpicked collection of fresh work from the creative community.",
    "Yesterday",
    "Updates",
    false,
    false,
    "D",
    "pink",
  ],
  [
    "Noah Williams",
    "noah@studio.co",
    "Re: Friday team lunch",
    "Count me in! That place looks great. See everyone there at 12:30.",
    "Yesterday",
    "Personal",
    false,
    false,
    "NW",
    "blue",
  ],
  [
    "Ava Thompson",
    "ava@studio.co",
    "Updated project timeline",
    "I’ve made a few adjustments to the timeline based on our conversation.",
    "Sep 27",
    "Projects",
    false,
    false,
    "AT",
    "orange",
  ],
  [
    "GitHub",
    "notifications@github.com",
    "[studio/website] Pull request merged",
    "The new navigation component has been merged into the main branch.",
    "Sep 27",
    "Updates",
    false,
    false,
    "GH",
    "slate",
  ],
];

export const demoMessages = conversations.map((item, index) => {
  const [
    sender,
    email,
    subject,
    preview,
    time,
    label,
    unread,
    starred,
    initials,
    color,
    body,
    attachment,
  ] = item;
  return {
    id: `demo-${index}`,
    sender,
    email,
    subject,
    preview,
    time,
    label,
    unread,
    starred,
    initials,
    color,
    folder: "Inbox",
    date: `2026-09-${index < 6 ? "29" : index < 10 ? "28" : "27"}T${String(12 - (index % 6)).padStart(2, "0")}:00:00`,
    body:
      body ||
      `Hi Alex,\n\n${preview}\n\nLet me know what you think when you have a moment. Happy to discuss any questions.\n\nBest,\n${sender}`,
    attachments: attachment
      ? [
          {
            name: attachment,
            size: "1 KB",
            content:
              "Website redesign brief\n\nScope: refreshed navigation, typography, and responsive product pages.\nReview: Thursday.\nOwner: Sophia Chen.",
          },
        ]
      : [],
  };
});

demoMessages.push(
  {
    ...demoMessages[1],
    id: "sent-1",
    sender: "Me",
    email: currentUser.email,
    to: "james@studio.co",
    subject: "Launch checklist — first draft",
    folder: "Sent",
    unread: false,
    starred: false,
    body: "Hi James,\n\nI’ve finished the first pass of our launch checklist. Let’s review it together tomorrow.\n\nThanks,\nAlex",
    initials: "AM",
  },
  {
    ...demoMessages[4],
    id: "draft-1",
    sender: "Me",
    email: currentUser.email,
    to: "product@studio.co",
    subject: "Ideas for our next sprint",
    folder: "Drafts",
    unread: false,
    starred: false,
    body: "Hi team,\n\nA few ideas I’d like us to explore in our next sprint:\n",
    initials: "AM",
  },
  {
    ...demoMessages[7],
    id: "outbox-1",
    sender: "Me",
    email: currentUser.email,
    to: "olivia@studio.co",
    subject: "Q3 campaign follow-up",
    preview:
      "Hi Olivia, thanks for sharing the campaign report. I have added a few notes for our review.",
    folder: "Outbox",
    unread: false,
    starred: false,
    body: "Hi Olivia,\n\nThanks for sharing the Q3 campaign report. I have added a few notes for our review and will walk through them with you tomorrow.\n\nBest,\nAlex",
    initials: "AM",
  },
  {
    ...demoMessages[0],
    id: "snooze-1",
    subject: "Website redesign feedback reminder",
    preview:
      "This conversation is snoozed until tomorrow morning so you can review the latest designs.",
    folder: "Snooze",
    unread: false,
    starred: false,
    time: "Tomorrow",
    body: "Hey Alex,\n\nThe latest website designs are ready for your review. I have incorporated the navigation and product-page feedback from our last session.\n\nThis conversation will return to your inbox tomorrow morning.\n\nBest,\nSophia",
  },
  {
    ...demoMessages[6],
    id: "archive-1",
    subject: "Last month’s studio meetup",
    folder: "Archive",
    unread: false,
  },
  {
    ...demoMessages[8],
    id: "spam-1",
    subject: "An offer you may have missed",
    folder: "Spam",
    unread: false,
  },
  {
    ...demoMessages[11],
    id: "trash-1",
    subject: "Old deployment notification",
    folder: "Trash",
    unread: false,
  },
  {
    ...demoMessages[4],
    id: "template-1",
    sender: "Me",
    email: currentUser.email,
    to: "",
    subject: "Project status update",
    preview:
      "A reusable weekly update with sections for progress, blockers, and next steps.",
    folder: "Template",
    unread: false,
    starred: false,
    time: "Saved",
    body: "Hi team,\n\nHere is this week’s project update.\n\nProgress\n• [Add completed work]\n\nBlockers\n• [Add current blockers]\n\nNext steps\n• [Add upcoming priorities]\n\nBest,\nAlex",
    initials: "AM",
  },
  {
    ...demoMessages[11],
    id: "notification-1",
    sender: "GitHub",
    email: "notifications@github.com",
    subject: "New activity in studio/website",
    preview:
      "James requested your review on the latest navigation update.",
    folder: "Notifications",
    unread: true,
    starred: false,
    time: "11:20 AM",
    body: "Hi Alex,\n\nJames Wilson requested your review on the latest navigation update in studio/website. Open the project when you are ready to review the changes.\n\nGitHub Notifications",
  },
  {
    ...demoMessages[2],
    id: "newsletter-1",
    subject: "The Studio Weekly — October edition",
    preview:
      "Fresh design inspiration, product updates, and community highlights for your week.",
    folder: "Newsletter",
    unread: true,
    starred: false,
    time: "8:15 AM",
    body: "Hi Alex,\n\nWelcome to this week’s Studio Weekly. Inside: three thoughtful design reads, a product workflow worth trying, and highlights from the creative community.\n\nHave a great week,\nThe Studio Weekly team",
  },
);

export const labels = [
  { name: "Work", dot: "bg-blue-400", badge: "bg-blue-50 text-blue-600" },
  {
    name: "Projects",
    dot: "bg-violet-400",
    badge: "bg-violet-50 text-violet-600",
  },
  {
    name: "Personal",
    dot: "bg-emerald-400",
    badge: "bg-emerald-50 text-emerald-600",
  },
  { name: "Updates", dot: "bg-amber-400", badge: "bg-amber-50 text-amber-700" },
];
